return table.freeze{
	trigger=table.freeze{
		"jumpscarez",
		"btt",
		"teamfat",
		"team fat",
		"teamf%*t",
		"lalol",
		"k00p",
		"c00l",
		"br4kidd",
		"br4kid",
		"tr3",
		"kaax",
		"l00p",
		"g00g",
		"tubers",
		"zyx0",
		"destroy complete",
		"noot noot",
		"server destruction",
		"shark blood",
		"sharkblood",
		"shark_blood",
		"666",
		"jumpscare",
		"nuke gui",
		"neko",
		"decal spam",
		"particle spam",
		string.reverse("emag kcuf"),
		string.reverse("revres kcuf"),
		"destroy server",
		"nuke server",
	},
	
	del=table.freeze{
		"stupid town",
		"h@ck3d,"
	},
}